### PR TITLE
layout changes, sort fix, readme

### PR DESCRIPTION
**Pull request by m1ga**
Just as an idea

Screenshot_20211004_163250

**Changes:**

* updated the readme with instructions
* fixed sorting (use lowercase for names)
* change the layout: App-header only for the header section, list items = li, make it a real list (more space)

_(got all my hacktoberfest poitns already :rofl: so don't merge it if you don't like the changes)_

### CODE REVIEW

**Comment by code-knackerin** [comment]
Hey m1ga, 
thanks for your idea. But the buttons are important than that tool is not finished. 
I have to click the button to push the item to another List. But the ReadMe instruction are nice. :) 
Great. I hope you get a tShirt ;) Happy day to you.

**Comment by m1ga** [comment]
I've remove everything besides the readme and the sort fix. So you can merge (or close) this PR if you want :+1:

**Comment by code-knackerin** [comment]
Yeah nice! thx. have a nice day :)

**Comment by m1ga** [comment]
@code-knackerin oh, please a a break behind the image! Looks like my editor included one but Github doesn't :smile:

**Pull request merged**
